# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  # api:
  #   image: browsergame-api
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Production
  #     - ASPNETCORE_URLS=http://+:80
  client:
    image: browsergame-client
    ports:
      - 80:80
      - 443:443
    environment:
      - ENVIRONMENT=Production
    depends_on:
      - db_cluster
  # cache:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  db_cluster:
    container_name: db_cluster
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip", "db_cluster" ]
    depends_on:
      - db1
      - db2
      - db3
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
  db1:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip", "db1" ]
    expose:
      - 27018
    ports:
      - '27018:27017'
  db2:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip", "db2" ]
    expose:
      - 27019
    ports:
      - '27019:27017'
  db3:
    image: mongo
    command: [ "--replSet", "rs0", "--bind_ip", "db3" ]
    expose:
      - 27020
    ports:
      - '27020:27017'
