# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  api:
    image: browsergame-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
  client:
    image: browsergame-client
    ports:
      - 80:80
      - 443:443
    environment:
      - ENVIRONMENT=Production
