name: API - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Main.sln
    - name: Build
      run: dotnet build Main.sln --no-restore
    - name: Test
      run: dotnet test api.tests\api.tests.csproj --no-build --verbosity normal
